# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
