# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='blog/static/category_cover/'),
        ),
    ]
