# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180412_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, upload_to='static/attachment/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(upload_to='static/cover/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(default='static/category_cover/default.png', upload_to='static/category_cover/'),
        ),
    ]
